spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://124.71.213.221:3306/xiaofanguan?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8



# Log4j Configuration
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.xiaofanguan.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.xiaofanguan.server.mapper: debug


minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: demo

wechat:
  miniapp:
    app-id: 你的小程序appId
    app-secret: 你的小程序appSecret


